version: "3.7"

services:
  app:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - BOT_TOKEN
      - REDIS_HOST
      - REDIS_PORT
      - ALLOWED_USERS

  redis:
    image: redis:7-alpine
